project_id = "qzckpzwhkevqhwywlrkf"

[functions.update-user]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-scoresheet-email]
verify_jwt = false

[functions.send-review-email]
verify_jwt = false
