project_id = "qzckpzwhkevqhwywlrkf"

[functions.update-user]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-scoresheet-email]
verify_jwt = false

[functions.send-review-email]
verify_jwt = false

[functions.competitionList]
verify_jwt = false

[functions.getMobileAppVersion]
verify_jwt = false

[functions.getDropboxSetting]
verify_jwt = false

[functions.uniqueTeamName]
verify_jwt = false

[functions.login]
verify_jwt = false

[functions.forgotPassword]
verify_jwt = false

[functions.create_password]
verify_jwt = false

[functions.mobile-coach-events]
verify_jwt = false

[functions.mobile-coach-teams]
verify_jwt = false

[functions.brightcove-upload-init]
verify_jwt = false

[functions.brightcove-upload-complete]
verify_jwt = false

[functions.brightcove-ingest-callback]
verify_jwt = false

[functions.logout]
verify_jwt = false

[functions.me]
verify_jwt = false

[functions.mobile-submission]
verify_jwt = false



