project_id = "qzckpzwhkevqhwywlrkf"

[functions.update-user]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-scoresheet-email]
verify_jwt = false

[functions.send-review-email]
verify_jwt = false

[functions.competitionList]
verify_jwt = false

[functions.getMobileAppVersion]
verify_jwt = false

[functions.getDropboxSetting]
verify_jwt = false

[functions.uniqueTeamName]
verify_jwt = false

